Mission2Assignment/Models/gradecalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2Assignment.Models
{
    public class gradecalcModel
    {
        //make all fields required and need to be between 0-100
        [Required]
        [Range(0, 100)]
        public int Assignments { get; set; }

        [Required]
        [Range(0, 100)]
        public int GroupProjects { get; set; }

        [Required]
        [Range(0, 100)]
        public int Quizzes { get; set; }

        [Required]
        [Range(0, 100)]
        public int Exams { get; set; }

        [Required]
        [Range(0, 100)]
        public int Intex { get; set; }
    }
}

Mission2Assignment/Controllers/BrinleyController.cs
using Microsoft.AspNetCore.Mvc;
using Mission2Assignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2Assignment.Controllers
{
    public class BrinleyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //Create getter and setting for grade calculation form page

        [HttpGet]
        public IActionResult gradecalc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult gradecalc(gradecalcModel model)
        {
            return View();
        }
    }
}

Mission2Assignment/Views/Brinley/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Brinley's Website";
}


    <!-- Page title and image -->
    <h1>Brinley Miller</h1>
    <center><img src="img/starwars.jpg" width="600" /></center>

    <!-- Paragraph about myself -->
    <p>
        I recently got a job as a Web Developer at BYU. I was very excited to get this job, but also
        very nervous because it was in C# which I have never coded in. I hope to be able to gain confidence
        in my C# sharp coding abilities in this class. I want to be able to use this confidence to create
        my own website or app. I also want to have a further understanding of the MVC model because I occassionally get
        confused on where specific code should be.
    </p>

    <!-- List of top 3 Jobs -->
    <div>
        <h3>Top #3 Jobs</h3>
        <ol>
            <li>Web Development</li>
            <li>Software Test Engineer</li>
            <li>UI/UX</li>
        </ol>
    </div>

    

    

Mission2Assignment/Views/Brinley/gradecalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Grade Calculator";
}
<!-- grade calculator form -->
@model gradecalcModel;
<h2>Grade Calculator</h2>
<form method="post">
    <label for="assignments"> Assignments:</label>
    <input id="assignments" type="number" asp-for="Assignments" />%<br /><br />
    <label for="groupproject" id="ec">Group Projects:</label>
    <input id="groupproject" type="number" asp-for="GroupProjects"/>%<br /><br />
    <label for="quizzes">Quizzes:</label>
    <input type="number" id="quizzes" asp-for="Quizzes" />%<br /><br />
    <label for="exams">Exams:</label>
    <input type="number" id="exams" asp-for="Exams" />%<br /><br />
    <label for="intex">INTEX:</label>
    <input type="number" id="intex" asp-for="Intex"/>%<br /><br />

    <!-- submit button for calculator -->
    <input class="btnGrade" id="btnGrade" type="submit" value="Calculate Grade" />

    <div id="summary" asp-validation-summary="All"></div>
</form>

Mission2Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width-device-width" />
    <meta charset="utf-8" />
    <link rel="icon" type="image/x-icon" href="img/logo.jpg" />
    @* Allow for there to be a different title on each page *@
    <title>@ViewBag.Title</title>

    <!-- Link in css stylesheets -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />

</head>
<body>
    @* Navigation bar *@
    <nav>
        <a asp-controller="Brinley" asp-action="Index">Home</a>
        <a asp-controller="Brinley" asp-action="gradecalc">Grade Calculator</a>

    </nav>
    <div>
        @RenderBody()
    </div>


    <!-- links to js and jquery -->
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/lib/jquery/jquery-3.6.0.min (1).js"></script>
    <script src="~/js/script.js"></script>
</body>
</html>